---
# Common role - default variables
# These can be overridden in vars/user_environment.yml

target_user: moshpit
user_shell: /bin/bash

common_packages:
  - vim
  - curl
  - wget
  - git
  - htop
  - tree

bash_aliases: {}
environment_variables: {}
git_config: {}
vm_swappiness: 10
enable_unattended_upgrades: false
